# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='admin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
