# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_room', '0004_auto_20170127_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='prev_id',
        ),
        migrations.AlterField(
            model_name='slide',
            name='next_id',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
