# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_room', '0007_remove_room_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='md_blob',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='next_id',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
