# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import manage_chat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_room', '0003_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAndReply',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('hash_value', models.CharField(default=manage_chat.models._createHash, max_length=10, unique=True)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reply', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
            ],
        ),
    ]
