# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_room', '0003_slide'),
        ('manage_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatandreply',
            name='room',
            field=models.ForeignKey(default='hello', on_delete=django.db.models.deletion.CASCADE, to='manage_room.Room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='room',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='manage_room.Room'),
            preserve_default=False,
        ),
    ]
