# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chat', '0002_auto_20170126_0018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='description',
            new_name='answer',
        ),
        migrations.AddField(
            model_name='poll',
            name='answer_count',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poll',
            name='question',
            field=models.CharField(default='test', max_length=130),
            preserve_default=False,
        ),
    ]
