# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chat', '0003_auto_20170129_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatandreply',
            name='assist_hash',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
