# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 00:15
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_chat', '0006_poll_hash_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='answer',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='poll',
            name='answer_count',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
